spring:
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      username: mongo
      password: mongo
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  application:
    name: customer-service
